### ISSUE TITLE
Design of "Dane Dziecka" component

### ISSUE THREAD

**Issue by Rafalkufel** [CodeForPoznan/alinka-electron#50]

**Comment by Rafalkufel** [comment]
Looks great. Readable and user friendly. But I have some suggestions.
* Can you please explain that "inna deklinacja imienia i nazwiska....". When it comes to polish names nominative differs from genitive each time. Isn't it? So I think this checkbox seems to be redundant.
* Can we change "Miejsce zamieszkania" to "Miejscowość". I'm affraid that "Miejsce zamieszkania" can confuse user, what value should be inserted there....
* Can we switch places of "klasa" and "zawód". I think that the former will be more offen used.
* "Szkoła" field should be also a `dropdown`
* And the new question of parents data. with button like (the same as child address.)

**Comment by agatakozinska** [comment]
* Yep, my bad. Somehow I thought it can be the same... I will fix this one and will change "Miejsce zamieszkania" to "Miejscowość"

> Can we switch places of "klasa" and "zawód". I think that the former will be more offen used.

About that, the idea was that input with "zawód"/ "klasa" only will show up when the right school will be chosen, otherwise, I can be weird to leave an input empty? 

> "Szkoła" field should be also a dropdown 

But do we have some database with all the schools? What happens in case if there is a new school, there is no option to add one, right? 

>And the new question of parents data. with button like (the same as child address.)
 
Button? Don't understand.

**Comment by Rafalkufel** [comment]
https://www.figma.com/file/eggpYIDsUJya3rgOcXqyuC05/Alinka-design?node-id=2%3A1
